# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c584ea914ff7b1058ff9ea4a8d8281324f00ac7f50ceda14c4c190ec493b3a683939e7efc959e97015ec7efe18f397ffc832cb30f1c8c21b4dbb3c925197be75

test:
  secret_key_base: c283e64fe551083fc066ba2d2e5b28dd521ce9a6fed0ab1b4be15c040afbc2d17fcd0aa8e6093e0b2e8031c4c0f027aee2fed87a1d6d0e5c141057994a791040

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
